### PR TITLE
Creating test cluster using Argo/CAPI

### PR DESCRIPTION
**Pull request by DaveW-STFC**
Configuration files to create a new test cluster under the dev env within my own scratch environment. Hopefully!

### CODE REVIEW

**Comment by DavidFair** [comment]
Nit: can we rename it to something like `DaveW` instead of your fed ID so we don't have to map back?

**Comment by anish-mudaraddi** [comment]
just be aware your cluster name will be `dev-<whatever name you give it>-cluster` - so you might want to keep it short :)

**Comment by anish-mudaraddi** [comment]
you'll want to rotate the `secrets/dev/smtp-smarthost.yaml` secret to add your age key as well

**Review by RJaliliSTFC — APPROVED** [review]

**Comment by RJaliliSTFC** [comment]
> you'll want to rotate the `secrets/dev/smtp-smarthost.yaml` secret to add your age key as well

Just need to look at this @DaveW-STFC

**Review by RJaliliSTFC — APPROVED** [review]

**Pull request merged**
